import './js/vars';
import QueueService from './js/queue-service';
import './js/movies-api-service';
import './js/movies';
import './js/modal-movie';
import './js/trailer';
import './js/movies-on-search';
import './js/watched_queue_button';
import './js/pagination_main';
import './js/loading';
import './js/modal-card';
